import { NextResponse } from "next/server";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

/**
 * GET /api/corpus
 *
 * Serves corpus-metadata.json from public/ (generated at build time
 * or regenerated by the admin API after document saves).
 */
export async function GET(): Promise<NextResponse> {
  try {
    const file = join(process.cwd(), "public", "corpus-metadata.json");
    if (existsSync(file)) {
      const data = readFileSync(file, "utf-8");
      return new NextResponse(data, {
        headers: {
          "Content-Type": "application/json",
          "Cache-Control": "no-cache",
        },
      });
    }

    return NextResponse.json(
      { error: "Corpus data not available" },
      { status: 404 },
    );
  } catch (err) {
    console.error("[api/corpus]", err);
    return NextResponse.json(
      { error: "Failed to load corpus data" },
      { status: 500 },
    );
  }
}
