import { NextResponse } from "next/server";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

/**
 * GET /api/graph
 *
 * Serves entity-graph.json from public/ (generated at build time
 * or regenerated by the admin API after document saves).
 */
export async function GET(): Promise<NextResponse> {
  try {
    const file = join(process.cwd(), "public", "entity-graph.json");
    if (existsSync(file)) {
      const data = readFileSync(file, "utf-8");
      return new NextResponse(data, {
        headers: {
          "Content-Type": "application/json",
          "Cache-Control": "public, max-age=60, stale-while-revalidate=300",
        },
      });
    }

    return NextResponse.json(
      { error: "Entity graph data not available" },
      { status: 404 },
    );
  } catch (err) {
    console.error("[api/graph]", err);
    return NextResponse.json(
      { error: "Failed to load entity graph data" },
      { status: 500 },
    );
  }
}
